baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
first_name = "shreyas"
last_name = "sneh"
hero_subtext = "Software Engineer | Problem Solver | Tech Enthusiast"
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
